### ISSUE TITLE
Weird progress prints

### ISSUE THREAD

**Issue by jeiglsperger** [uchidalab/time_series_augmentation#3]
Hi,

while executing the aug.discriminative_guided_warp() method, I get weird progress print, not like the self-filling progress bar as it should appear, but instead like this:
```
  1%|▊                                                                                                                                                       | 6/1086 [00:00<00:23, 45.20it/s]
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
  2%|███▊                                                                                                                                                   | 27/1086 [00:00<00:18, 58.39it/s]
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
There is only one pattern of class 0
```

Is there a way to suppress this?

Kind regards!

**Comment by biwana** [comment]
That warning is there because some of the augmentation methods requires two or more patterns within a class. This is because these augmentation methods combine multiple patterns together. If there is only one pattern, there is nothing to combine.

I can add a setting so verbose will turn the warning off, but I don't suggest using those particular methods when you have a class with only one pattern.

**Comment by jeiglsperger** [comment]
Ok, I don't quite understand the principle of the error message `There is only one pattern of class 0`. 
I commented the print of the string out, so the progress bar functions normally.

**Comment by biwana** [comment]
It just means one of your classes (the first one in your particular case) only has one example in your entire training dataset. The data augmentation method you are trying to use requires more than one, otherwise it's not doing anything for patterns in that class.

I added some flags (verbose=-1) to hide the warning. But, commenting that line is effectively the same, there is no harm, it's only a warning.

**Comment by jeiglsperger** [comment]
I'm sorry for asking again but I'm confused by the concept of classes. What exactly is meant by that?
