### ISSUE TITLE
CUDA support and theoretical question

### ISSUE THREAD

**Issue by jeiglsperger** [uchidalab/time_series_augmentation#5]
Hi!

DGW does in my case not use gpu, even though one would be available.  From the code, I see that theoretically, CUDA support should be available. Does anyone else have a similar problem?

Also, I have a theoretical question: would you classify your model as a machine learning model? DGW does not actually use a neural network if I read the code correctly.

Kind regards!

**Comment by biwana** [comment]
Hi,

You are correct, it doesn't use GPU (because it was written in Numpy). It's possible to re-write it in a library such as tensorflow or pytorch to use GPU, or to write it in cuda directly. But, I didn't do that.

Of all of the time series augmentation methods in this repository, DGW is probably the only one that I would say that it qualifies to be a machine learning model. This is because the discriminator. It doesn't use a neural network, but neural networks are only one of the many machine learning algorithms.
